name: Astro Studio

env:
  ASTRO_STUDIO_APP_TOKEN: ${{secrets.ASTRO_STUDIO_APP_TOKEN }}
  NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  DB:
    permissions:
      contents: read
      actions: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install package manager
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          architecture: x64
          node-version: 20
          cache: yarn
          cache-dependency-path: |
            ./yarn.lock
            ./package.json
            ./.yarnrc.yml
      
      - name: Setup .yarnrc.yml
        run: |
          yarn config set npmScopes.my-org.npmRegistryServer "https://npm.pkg.github.com"
          yarn config set npmScopes.my-org.npmAlwaysAuth true
          yarn config set npmScopes.my-org.npmAuthToken $NPM_AUTH_TOKEN
          yarn config set cacheFolder ./.yarn/cache
          yarn config set nodeLinker node-modules
          yarn config set enableTelemetry false
          yarn config set enableGlobalCache false
          yarn config set enableMirror true
      - uses: jaid/action-npm-install@v1.2.1
        with:
          nodeEnv: development
          packageManager: yarn
      - uses: withastro/action-studio@main
