name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    permissions:
      contents: read
      actions: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        architecture: x64
        node-version: 20.11.1
        cache: yarn
        cache-dependency-path: |
          ./yarn.lock
          ./package.json
          ./.yarnrc.yml
    - name: Setup .yarnrc.yml
      run: |
        yarn config set npmScopes.my-org.npmRegistryServer "https://npm.pkg.github.com"
        yarn config set npmScopes.my-org.npmAlwaysAuth true
        yarn config set npmScopes.my-org.npmAuthToken $NPM_AUTH_TOKEN
        yarn config set cacheFolder ./.yarn/cache
        yarn config set nodeLinker node-modules
        yarn config set enableTelemetry: false
        yarn config set enableGlobalCache: false
      env:
        NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: jaid/action-npm-install@v1.2.1
      with:
        nodeEnv: production
        packageManager: yarn
    - run: yarn build
